name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "test"

      - name: test
        env:
          THE_HASH: ${{ hashFiles('test/foo') }}
        run: echo $THE_HASH && exit 1
